//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Model
{
    using System.Runtime.Serialization;using System;
    using System.Collections.Generic;
    [DataContract] public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.ReporteEntregado = new HashSet<ReporteEntregado>();
        }
    
        [DataMember] public int IdArticulo { get; set; }
        [DataMember] public int IdCategoria { get; set; }
        [DataMember] public int IdEstado { get; set; }
        [DataMember] public string Marca { get; set; }
        [DataMember] public string Descripcion { get; set; }
        [DataMember] public byte[] Foto { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteEntregado> ReporteEntregado { get; set; }
    }
}
