//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Model
{
    using System.Runtime.Serialization;using System;
    using System.Collections.Generic;
    [DataContract] public partial class ReporteExtravio
    {
        [DataMember] public int IdReporte { get; set; }
        [DataMember] public int IdUsuario { get; set; }
        [DataMember] public System.DateTime Fecha { get; set; }
        [DataMember] public string Descripcion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
