//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Model
{
    using System.Runtime.Serialization;using System;
    using System.Collections.Generic;
    [DataContract] public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.ReporteEntregado = new HashSet<ReporteEntregado>();
            this.ReporteExtravio = new HashSet<ReporteExtravio>();
        }
    
        [DataMember] public int idUsuario { get; set; }
        [DataMember] public string Nombre { get; set; }
        [DataMember] public string Apellido1 { get; set; }
        [DataMember] public string Apellido2 { get; set; }
        [DataMember] public string Contrasenia { get; set; }
        [DataMember] public Nullable<int> IdRol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteEntregado> ReporteEntregado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteExtravio> ReporteExtravio { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
